
FROM centos
MAINTAINER ahojcn<ahojcn@qq.com>


ENV MY_PATH /usr/local/
WORKDIR $MY_PATH


RUN yum -y install vim
RUN yum -y install net-tools


EXPOSE 80
CMD echo $MY_PATH
CMD echo "success --- ok"
CMD ["/bin/bash"]

