# Generated by Django 2.2.3 on 2019-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('school_addr', models.CharField(max_length=30)),
                ('school_build_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_birth', models.DateTimeField()),
                ('stu_gender', models.BooleanField()),
                ('stu_school', models.ForeignKey(on_delete=None, to='booktest.School')),
            ],
        ),
    ]
